name: .NET

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish for Windows
      run: dotnet publish -r win-x64 --self-contained
    - uses: actions/upload-artifact@v2
      with:
        name: Orleans.Sample.Web-${{ github.head_ref }}-win-x64
        path: src/Orleans.Sample.Web/bin/Debug/net5.0/win-x64/publish
    - name: Publish for Linux
      run: dotnet publish -r linux-x64 --self-contained
    - uses: actions/upload-artifact@v2
      with:
        name: Orleans.Sample.Web-${{ github.head_ref }}-linux-x64
        path: src/Orleans.Sample.Web/bin/Debug/net5.0/linux-x64/publish
